name: mcsports-lobby
version: '1.0'
authors: [ 'mcsports', 'Jannik' ]
api-version: '1.21'
main: club.mcsports.lobby.Lobby

dependencies:
  server:
    simplecloud-api:
      load: BEFORE
      required: true
      join-classpath: true
    SimpleCloud-Player:
      load: BEFORE
      required: true
      join-classpath: false